name: YeOldeShoppe
main: cc.ekblad.yeoldeshoppe.YeOldeShoppe
version: 0.1

commands:
    ywp:
        description: Add and remove waypoints.
        usage: /<command> add Name of waypoint OR /<command> del Name of waypoint
        permission: yeoldeshoppe.warps
        permission-message: Sorry, you can't do that!

permissions:
    yeoldshoppe.opshop:
        description: Allows you to destroy and access the inventory of shops you do not own
        default: op
    yeoldeshoppe.warps:
        description: Place and remove waypoints.
        default: op